// GENERATED by webapp/tools/build-brand.mjs from webapp/brand.json — do not edit this file.
//
// The white-label identity, as data. `brand.json` is the source; `brand.css` is
// the other half of the same generation and carries the palette, the mark and the
// marker `applySettings()` reads.
export const BRAND = Object.freeze({
  "name": "OpenDoc",
  "named": false,
  "tabTitle": "document+product",
  "mark": "./opendoc-mark.svg",
  "themed": false,
  "accentPinned": false
});

/** Host string overrides, by locale tag, with `*` meaning every language.
 *
 *  Installed through `setOverrides` in `i18n.mjs` — the SAME lookup the
 *  nineteen catalogues resolve through, one layer earlier. There is deliberately
 *  no second string mechanism for hosts (`docs/126` phase 3). */
export const BRAND_STRINGS = Object.freeze({});
