[package]
name = "opendoc-fuzz"
version = "0.0.0"
publish = false
edition = "2024"
rust-version = "1.88.0"
license = "Apache-2.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
casual-doc-package = { path = "../crates/casual-doc-package", version = "=0.0.1" }
casual-doc-ooxml = { path = "../crates/casual-doc-ooxml", version = "=0.0.1" }
casual-doc-odf = { path = "../crates/casual-doc-odf", version = "=0.0.1" }
libfuzzer-sys = "=0.4.13"

[[bin]]
name = "bounded_package"
path = "fuzz_targets/bounded_package.rs"
test = false
doc = false
bench = false

[[bin]]
name = "docx_package"
path = "fuzz_targets/docx_package.rs"
test = false
doc = false
bench = false

[[bin]]
name = "odt_package"
path = "fuzz_targets/odt_package.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
resolver = "3"
