// `packages/opendoc-embed` — the guards that make it a real artifact rather
// than a manifest nobody can install.
//
// `docs/126` phase 1 asks for "a single installable artifact", and `docs/99` §9
// is the reason this file exists at all: a published claim has to be derived
// from a committed artifact, and "installable" is a published claim. So this
// checks the three ways it could be false —
//
//   * the generated files have drifted from the authority they are copied and
//     derived from, so the package and the editor disagree about what
//     `readonly` means;
//   * the manifest points at files the tarball does not contain, so the install
//     succeeds and the import fails;
//   * the typings name members the class does not have, so a host's build
//     passes and their code does not run.
//
// What it cannot check is whether anything published it; nothing does yet, and
// the package README says so rather than implying otherwise.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const WEBAPP = dirname(dirname(fileURLToPath(import.meta.url)));
const REPO = dirname(WEBAPP);
const PACKAGE = join(REPO, "packages", "opendoc-embed");
const GENERATOR = join(WEBAPP, "tools", "build-embed-package.mjs");

const manifest = JSON.parse(readFileSync(join(PACKAGE, "package.json"), "utf8"));

/** Every path the manifest promises a consumer, relative to the package. */
function declaredEntryPoints() {
  const paths = new Set();
  for (const field of ["main", "module", "types"]) {
    if (manifest[field]) paths.add(manifest[field]);
  }
  const walk = (value) => {
    if (typeof value === "string") paths.add(value);
    else if (value && typeof value === "object") Object.values(value).forEach(walk);
  };
  walk(manifest.exports);
  return [...paths];
}

test("the generated files are what a fresh generation produces", () => {
  // The same shape `build_site.test.mjs` uses: run the generator's `--check`
  // and let a non-zero exit fail the test. `execFileSync` throws on non-zero,
  // so this cannot pass while the files are stale — and it is NOT piped into
  // anything, because reading a pipe's exit status is how a formatting failure
  // once reached CI looking green (SKILL.md §3).
  execFileSync("node", [GENERATOR, "--check"], { cwd: REPO, stdio: "pipe" });
});

test("every module in the package is its webapp/src authority, verbatim", () => {
  // Byte equality after the banner, not "looks similar". A transformed copy is a
  // second implementation of the permission rules, and two implementations of
  // one rule diverge (SKILL.md §8). Enumerated from the package rather than from
  // a list here, so a module added to the package without an authority fails
  // this rather than sitting unchecked.
  //
  // `release.mjs` is the one module that is DERIVED rather than copied — its
  // fields come from `package.json`, `Cargo.toml` and the host contract, not from a
  // `webapp/src` twin — so it is excluded here and re-derived by its own test
  // below. Excluded by NAME rather than by "has no authority", because "skip
  // anything with no authority" would silently exempt the next module somebody
  // forgets to give one.
  const DERIVED = new Set(["release.mjs"]);
  const all = readdirSync(join(PACKAGE, "src")).filter((name) => /\.(mjs|js)$/.test(name));
  const copies = all.filter((name) => !DERIVED.has(name));
  assert.ok(copies.length >= 3, `only ${copies.length} copied module(s) in the package`);
  for (const name of DERIVED) {
    assert.ok(all.includes(name), `${name} is exempted from the verbatim rule but is not there`);
  }
  for (const name of copies) {
    const authority = readFileSync(join(WEBAPP, "src", name), "utf8");
    const copy = readFileSync(join(PACKAGE, "src", name), "utf8");
    assert.ok(copy.endsWith(authority), `${name} is not its authority verbatim`);
    assert.match(copy, /^\/\/ GENERATED by webapp\/tools\/build-embed-package\.mjs/);
  }
});

test("every path the manifest promises exists", () => {
  const missing = declaredEntryPoints().filter((path) => !existsSync(join(PACKAGE, path)));
  assert.deepEqual(missing, [], "the manifest points at files that are not there");
});

test("the manifest declares what an installable package has to declare", () => {
  assert.equal(manifest.name, "@casualoffice/opendoc-embed");
  assert.equal(manifest.type, "module");
  assert.equal(manifest.license, "Apache-2.0");
  assert.ok(manifest.main, "no main: `require`/`import` of the bare name resolves to nothing");
  assert.ok(manifest.types, "no types: a TypeScript host gets `any`");
  assert.ok(manifest.exports?.["."], "no root export condition");
  assert.ok(Array.isArray(manifest.files) && manifest.files.length, "no files: publishes the lot");
  assert.match(manifest.version, /^\d+\.\d+\.\d+$/);
});

test("`files` covers every path the manifest promises", () => {
  // A path under `exports` that `files` does not include installs as a 404 —
  // the failure mode where `npm install` succeeds and the first import throws.
  const roots = manifest.files.map((entry) => entry.replace(/^\.\//, "").replace(/\/$/, ""));
  const uncovered = declaredEntryPoints().filter((path) => {
    const clean = path.replace(/^\.\//, "");
    return !roots.some((root) => clean === root || clean.startsWith(`${root}/`));
  });
  assert.deepEqual(uncovered, [], "these entry points would not be published");
});

test("the package has no runtime dependencies", () => {
  // Embeddability is the product (SKILL.md §1) and "no mandatory server, React,
  // or collaboration provider dependency" is a design rule (AGENTS.md). A host
  // pulling a transitive tree in to put an editor on a page is that rule being
  // broken quietly.
  assert.deepEqual(manifest.dependencies ?? {}, {});
  assert.deepEqual(manifest.peerDependencies ?? {}, {});
});

test("the element module stays independent of the editor page", () => {
  const source = readFileSync(join(WEBAPP, "src", "embed_element.mjs"), "utf8");
  // It must not reach into the 16k-line editor module: the whole of HF-085 is
  // that nothing can, and a package that imported it would be unpublishable as
  // well as wrong.
  assert.doesNotMatch(source, /from\s+["'][^"']*main\.js["']/);
  // Its imports are the two PURE modules that decide what an embed is: the
  // capability authority, and the translation from the competitor's
  // configuration onto it. Pinned as a closed list, because the property being
  // protected is that the element depends on nothing with a DOM, an engine or a
  // locale in it — "is this the same contract the editor resolves?" only has an
  // answer while that holds. `host_options.mjs` states in its own header that it
  // is not a second statement of what a capability or a region is; it reads both
  // vocabularies back out of `capabilities.mjs`, and `host_options.test.mjs`
  // fails on a row that names anything they do not contain.
  const imports = [...source.matchAll(/^import .*?from\s+["']([^"']+)["']/gms)].map((m) => m[1]);
  assert.deepEqual(imports, ["./capabilities.mjs", "./host_options.mjs"]);
  // And that second module is pure too, or the first assertion above is only
  // true one level deep.
  const options = readFileSync(join(WEBAPP, "src", "host_options.mjs"), "utf8");
  const optionImports = [...options.matchAll(/^import .*?from\s+["']([^"']+)["']/gms)].map((m) => m[1]);
  assert.deepEqual(optionImports, ["./capabilities.mjs"]);
});

test("importing the package outside a browser does not throw", async () => {
  // `class X extends HTMLElement` throws at MODULE EVALUATION where there is no
  // DOM, so a host that server-renders would crash on the import itself — most
  // React and Vue hosts do server-render. This is the one property of the
  // package that node can prove directly, so it does.
  const module = await import(join(WEBAPP, "src", "embed_element.mjs"));
  assert.equal(typeof module.OpenDocEditorElement, "function");
  assert.equal(module.OPENDOC_EDITOR_TAG, "opendoc-editor");
  // And registering is a no-op rather than a crash where there is no registry.
  assert.equal(module.defineOpenDocEditor(), false);
});

test("the typings describe the class that exists", async () => {
  // A `.d.ts` is not type-checked against its implementation by anything here,
  // so a member renamed in the class and left in the types compiles for a host
  // and fails at runtime. This reads the declared members back off the real
  // class instead.
  const types = readFileSync(join(PACKAGE, "types", "index.d.ts"), "utf8");
  const body = types.match(/declare class OpenDocEditorElement[^{]*\{([\s\S]*?)\n\}/)?.[1];
  assert.ok(body, "the typings no longer declare the element class");
  const declared = [...body.matchAll(/^\s*(?:readonly\s+)?([A-Za-z_]\w*)\s*[(:]/gm)].map(
    (match) => match[1],
  );
  assert.ok(declared.length >= 6, `only ${declared.length} members declared`);

  const { OpenDocEditorElement } = await import(join(WEBAPP, "src", "embed_element.mjs"));
  const own = Object.getOwnPropertyNames(OpenDocEditorElement.prototype);
  const phantom = declared.filter((name) => !own.includes(name));
  assert.deepEqual(phantom, [], "the typings declare members the class does not have");
});

test("the typings cannot claim a role or capability the code does not have", async () => {
  const types = readFileSync(join(PACKAGE, "types", "index.d.ts"), "utf8");
  const { CAPABILITIES, ROLES, PRESET_NAMES } = await import(
    join(WEBAPP, "src", "capabilities.mjs")
  );
  const literals = (name) => {
    const line = types.match(new RegExp(`export type ${name} = (.*);`))?.[1] ?? "";
    return line
      .split("|")
      .map((part) => part.trim().replace(/^"|"$/g, ""))
      .filter(Boolean);
  };
  assert.deepEqual(literals("Capability"), [...CAPABILITIES]);
  assert.deepEqual(literals("Role"), [...ROLES]);
  assert.deepEqual(literals("Mode"), [...PRESET_NAMES]);
});

test("the package packs, installs, and imports — not just claims to", async () => {
  // "Installable" is a published claim, and `docs/99` §9.1 is that a published
  // claim is derived from a committed artifact or it is not published. The other
  // tests here check the SHAPE of the manifest; this one does what a host does.
  // That is the whole difference between a manifest and a package, and it is the
  // reason this file gets to use the word "installable" at all.
  //
  // Offline on purpose: the package has no dependencies, so nothing legitimate
  // needs the network, and a gate that reaches a registry fails for reasons that
  // have nothing to do with the code.
  const scratch = mkdtempSync(join(tmpdir(), "opendoc-embed-install-"));
  try {
    const packed = execFileSync("npm", ["pack", "--silent", "--pack-destination", scratch], {
      cwd: PACKAGE,
      encoding: "utf8",
    })
      .trim()
      .split("\n")
      .pop();
    const tarball = join(scratch, packed);
    assert.ok(statSync(tarball).size > 0, "npm pack produced nothing");

    const consumer = join(scratch, "consumer");
    mkdirSync(consumer);
    writeFileSync(
      join(consumer, "package.json"),
      JSON.stringify({ name: "consumer", private: true, type: "module", version: "1.0.0" }),
    );
    execFileSync("npm", ["install", "--no-audit", "--no-fund", "--offline", tarball], {
      cwd: consumer,
      stdio: "pipe",
    });

    // Imported by the BARE SPECIFIER, resolved through `exports` — importing the
    // authority here would prove nothing about the package. The probe reports the
    // capability contract back so the round trip is checked, not just the resolve.
    const probe = join(consumer, "probe.mjs");
    writeFileSync(
      probe,
      [
        'import { ROLES, resolveCapabilities, editingModeFor, OpenDocEditorElement }',
        '  from "@casualoffice/opendoc-embed";',
        'import { resolveCapabilities as viaSubpath }',
        '  from "@casualoffice/opendoc-embed/capabilities";',
        'const readonly = [...resolveCapabilities({ mode: "readonly" })];',
        "process.stdout.write(",
        "  JSON.stringify({",
        "    roles: ROLES,",
        "    readonly,",
        '    mode: editingModeFor(resolveCapabilities({ mode: "readonly" })),',
        '    subpath: [...viaSubpath({ mode: "owner" })].length,',
        "    element: typeof OpenDocEditorElement,",
        "  }),",
        ");",
      ].join("\n"),
    );
    const out = JSON.parse(execFileSync("node", [probe], { cwd: consumer, encoding: "utf8" }));
    const { CAPABILITIES: caps, ROLES: roles } = await import(
      join(WEBAPP, "src", "capabilities.mjs")
    );
    assert.deepEqual(out.roles, [...roles], "the installed package has different roles");
    assert.deepEqual(out.readonly, ["print"]);
    assert.equal(out.mode, "viewing");
    assert.equal(out.subpath, caps.length);
    assert.equal(out.element, "function");
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
});

// ---- Release and provenance (`docs/126` phase 3) -----------------------------
// Every field in `src/release.mjs` is re-derived here FROM ITS SOURCE, not compared
// with itself. `docs/99` §9 rule 1: a published number is generated from a committed
// artifact or it is not published — and a host reads these to say which build they
// are running in a bug report, so a wrong one costs somebody an afternoon.
//
// The three versions are deliberately NOT collapsed into one. They answer different
// questions, and the guard is that each is what its own source says rather than that
// they agree with each other.

test("the release module is what its sources say, field by field", async () => {
  const { RELEASE } = await import(join(PACKAGE, "src", "release.mjs"));
  const { CONTRACT_VERSION } = await import(join(WEBAPP, "src", "host_contract.mjs"));
  const cargo = readFileSync(join(REPO, "Cargo.toml"), "utf8");
  const engine = cargo.match(/^\[workspace\.package\][\s\S]*?^version = "([^"]+)"/m)?.[1];

  assert.equal(RELEASE.package, manifest.name);
  assert.equal(RELEASE.version, manifest.version);
  assert.equal(RELEASE.licence, manifest.license);
  assert.equal(RELEASE.repository, manifest.repository.url);
  assert.equal(RELEASE.contract, CONTRACT_VERSION);
  assert.ok(engine, "the Cargo workspace version is no longer readable, so this guard checks nothing");
  assert.equal(RELEASE.engine, engine);
  // Frozen: a host that could mutate what they report is a host whose bug report
  // names a build that never existed.
  assert.equal(Object.isFrozen(RELEASE), true);
});

test("the release module claims no build commit, because a committed file cannot know one", () => {
  // The provenance trap, stated as an assertion. `stamp-assets.py` stamps
  // `GITHUB_SHA` at DEPLOY time; a committed file carrying a commit hash would be
  // fabricated provenance of exactly the kind `docs/99` §9 exists to prevent, and
  // it would be wrong for every build after the one that wrote it.
  const source = readFileSync(join(PACKAGE, "src", "release.mjs"), "utf8");
  const withoutUrls = source.replace(/https?:\/\/\S+/g, "");
  assert.equal(
    /\b[0-9a-f]{7,40}\b/.test(withoutUrls),
    false,
    "release.mjs carries something that looks like a commit hash",
  );
  assert.match(source, /stamped at DEPLOY time/);
});

test("the release module is reachable as a subpath, and typed", () => {
  // A fact a host cannot import is a fact they will hardcode.
  assert.ok(manifest.exports["./release"], "no ./release export condition");
  assert.equal(manifest.exports["./release"].import, "./src/release.mjs");
  const types = readFileSync(join(PACKAGE, "types", "index.d.ts"), "utf8");
  assert.match(types, /export declare const RELEASE: \{/);
  for (const field of ["package", "version", "contract", "engine", "licence", "repository"]) {
    assert.match(types, new RegExp(`readonly ${field}:`), `RELEASE.${field} is untyped`);
  }
});
