// `dict/glossary.txt` is DERIVED, and this is what keeps it derived.
//
// The owner asked for a product and industry glossary and, in the same breath,
// that it not be a hand-maintained list — because a hand-maintained list rots
// and then nobody trusts it. So the artifact is regenerated by
// `tools/build-glossary.mjs` from files already in the repository, and the test
// below **re-runs the generator and requires the committed file to match byte
// for byte**. That is the strongest form this guard can take: it fails on a
// hand edit, on a stale file after a rename, and on a change to the extraction
// rules that nobody regenerated for.
//
// It also asserts the things the derivation is SHAPED to guarantee, because
// "it matches the generator" is only worth having if the generator is right:
// our own names are in it, identifiers are not, and it is a different set from
// the user's personal dictionary.

import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";

import {
  MIN_FILES,
  MIN_OCCURRENCES,
  buildGlossary,
  ownNames,
  renderGlossary,
  stripCode,
} from "../tools/build-glossary.mjs";
import { isKnownWord, parseDictionary, parseGlossary } from "../src/spelling.mjs";

const committed = readFileSync(new URL("../dict/glossary.txt", import.meta.url), "utf8");
const glossary = parseGlossary(committed);
const enUS = parseDictionary(
  readFileSync(new URL("../dict/en-US.txt", import.meta.url), "utf8"),
);

test("the committed glossary is exactly what the generator derives, today", () => {
  assert.equal(
    renderGlossary(buildGlossary()),
    committed,
    "run `node tools/build-glossary.mjs` — the file is generated, and a hand " +
      "edit or a stale artifact after a rename both land here",
  );
});

test("our own product names are in it", () => {
  // The names the owner listed, in the words they used. Anything absent here
  // is a name the spell checker would flag in our own documentation.
  for (const name of [
    "opendoc",
    "OpenDoc",
    "opencalc",
    "CasualOffice",
    "casualoffice",
    "ONLYOFFICE",
    "OOXML",
    "DOCX",
    "ODT",
    "RTF",
    "WASM",
    "WebAssembly",
    "DrawingML",
    "WordprocessingML",
  ]) {
    assert.ok(glossary.has(name), `${name} is missing from the glossary`);
  }
});

test("a crate name is accepted whole, through its parts", () => {
  // No entry per crate: `isKnownWord` splits a hyphenated compound, so
  // `casual`, `doc` and `layout` cover every `casual-doc-*` there will ever be.
  assert.equal(isKnownWord("casual-doc-layout", enUS.all, { glossary }), true);
  assert.equal(isKnownWord("opendoc-render", enUS.all, { glossary }), true);
  assert.equal(
    glossary.has("casual-doc-layout"),
    false,
    "and the whole name is deliberately NOT an entry — admitting hyphenated " +
      "terms produced fragments like `byte-for` that are words in no language",
  );
});

test("identifiers and code do not get in", () => {
  const offenders = [...glossary].filter((term) => /[_./:\\\\]/.test(term));
  assert.deepEqual(
    offenders,
    [],
    "code spans and fenced blocks are stripped before tokenizing; an " +
      "identifier in the glossary means that strip regressed, and the glossary " +
      "would then be a mechanism for accepting typos rather than terms",
  );
  assert.ok(
    !glossary.has("effective"),
    "…and a word only ever seen inside an identifier is not vocabulary",
  );
});

test("the code strip removes spans, fences, link targets and bare URLs", () => {
  const stripped = stripCode(
    "Prose `identifier_here` more\n```\nfenced_block\n```\n[text](target/path.md) http://x.example/y\n",
  );
  assert.match(stripped, /Prose/);
  assert.match(stripped, /text/);
  for (const hidden of ["identifier_here", "fenced_block", "target", "x.example"]) {
    assert.ok(!stripped.includes(hidden), `${hidden} survived the strip`);
  }
});

test("a contraction does not leave its stem behind", () => {
  for (const artefact of ["didn", "doesn", "isn", "wasn", "hasn", "couldn"]) {
    assert.ok(
      !glossary.has(artefact),
      `${artefact} is not a word — it is half of a contraction, and a ` +
        "tokenizer that splits on the apostrophe puts it in",
    );
  }
});

test("nothing already in the dictionary is repeated here", () => {
  const repeated = [...glossary].filter((term) => enUS.all.has(term));
  assert.deepEqual(
    repeated.slice(0, 10),
    [],
    "a word is a word; carrying it twice only makes the file bigger and the " +
      "diff noisier",
  );
});

test("the glossary is sorted, non-empty and free of blank lines", () => {
  const terms = [...glossary];
  assert.ok(terms.length > 100, `only ${terms.length} terms`);
  assert.deepEqual(
    terms,
    [...terms].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0)),
    "codepoint order, so the artifact is diffable and reproducible",
  );
  assert.ok(terms.every((term) => term.trim() === term && term.length >= 3));
});

test("the thresholds are stated, so the trade-off is reviewable", () => {
  assert.ok(MIN_OCCURRENCES >= 2, "one mention is not vocabulary");
  assert.ok(MIN_FILES >= 2, "one document's subject is not the project's vocabulary");
});

test("our own names come from the files that define them, not from a list", () => {
  const names = ownNames();
  // `casual` and `doc` exist because the CRATES are called `casual-doc-*`;
  // `opendoc` because a crate and the package are. Renaming a crate changes
  // this set without anybody editing a word list.
  assert.ok(names.has("casual") && names.has("doc"));
  assert.ok(names.has("opendoc"));
});
