// Guards `docs/168-WORD-AND-DOCS-RIVAL-PLAN.md`, the plan to reach 85 on every
// fidelity stage and on editing parity. The plan's numbers are generated by
// `tools/build-rival-plan.mjs`; this test fails when they are stale, when an
// open capability in `docs/153` belongs to no batch or to two, when the plan
// names an id, a tracker row or a fidelity family that does not exist, and
// when the plan as written no longer reaches its own target.
import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import {
  build,
  capabilityVerdicts,
  fidelityRows,
  OPEN,
  parsePlan,
  project,
  STAGES,
  TARGET,
} from "../tools/build-rival-plan.mjs";

const PLAN = new URL("../../docs/168-WORD-AND-DOCS-RIVAL-PLAN.md", import.meta.url);
const BACKLOG = new URL("../../docs/109-BACKLOG.md", import.meta.url);
const text = readFileSync(PLAN, "utf8");
const plan = parsePlan(text);
const verdicts = capabilityVerdicts();

test("the plan's score blocks are generated from the current matrices", () => {
  assert.equal(
    build(text).text,
    text,
    "docs/168 is stale: run `node tools/build-rival-plan.mjs` from webapp/",
  );
});

test("every open docs/153 capability is in exactly one batch or deferred", () => {
  const seen = new Map();
  const place = (id, where) => {
    assert.ok(verdicts.has(id), `${where} names ${id}, which docs/153 does not list`);
    assert.ok(!seen.has(id), `${id} is in ${seen.get(id)} and in ${where}`);
    seen.set(id, where);
  };
  for (const batch of plan.batches) for (const id of batch.closes) place(id, `batch ${batch.order}`);
  for (const id of plan.deferred) place(id, "Deferred");
  const unassigned = [...verdicts]
    .filter(([id, { verdict }]) => OPEN.has(verdict) && !seen.has(id))
    .map(([id]) => id);
  assert.deepEqual(unassigned, [], "open capabilities with no batch");
  // A batch still to run must not claim what docs/153 already grades closed; a
  // done batch keeps its ids as the record of what it closed.
  const done = new Set(plan.batches.filter((b) => b.done).map((b) => `batch ${b.order}`));
  const closed = [...seen]
    .filter(([id, where]) => !done.has(where) && !OPEN.has(verdicts.get(id).verdict))
    .map(([id]) => id);
  assert.deepEqual(closed, [], "the plan schedules capabilities docs/153 already grades closed");
});

test("the batches run 1..N and name tracker rows that exist", () => {
  assert.deepEqual(
    plan.batches.map((batch) => batch.order),
    plan.batches.map((_, i) => i + 1),
  );
  const backlog = readFileSync(BACKLOG, "utf8");
  for (const batch of plan.batches) {
    for (const id of batch.ids) {
      assert.match(
        backlog,
        new RegExp(`^\\| (?:\\d+ \\| )?${id} \\|`, "m"),
        `batch ${batch.order} names ${id}, which docs/109 has no row for`,
      );
    }
  }
});

test("every move names a family the fidelity matrix grades, and raises it", () => {
  const rows = new Map(fidelityRows().map((row) => [row.family, row]));
  const weight = { full: 2, partial: 1 };
  for (const batch of plan.batches) {
    for (const { family, stage, value } of batch.moves) {
      assert.ok(rows.has(family), `batch ${batch.order} moves "${family}", which fidelity.js does not grade`);
      assert.ok(STAGES.includes(stage));
      if (batch.done) continue;
      assert.ok(
        (weight[rows.get(family)[stage]] ?? 0) < weight[value],
        `batch ${batch.order} moves ${family} ${stage} to ${value}, which it already is`,
      );
    }
  }
});

test("the plan as written reaches the target on all five measures", () => {
  const { steps } = project(fidelityRows(), verdicts, plan);
  const last = steps.at(-1).scores;
  for (const score of last) assert.ok(score >= TARGET, `the last batch leaves ${last.join(", ")}`);
});
