// GENERATED by webapp/tools/build-embed-package.mjs — do not edit.
//
// The unions below are emitted from the real exported values of
// webapp/src/capabilities.mjs, so a role or capability can never exist in the
// types without existing in the code, or the other way round.

/** Everything a host can grant or withhold. */
export type Capability = "open" | "new" | "save" | "download" | "print" | "edit" | "comment" | "branding" | "autosave";

/** The five roles, in strictly increasing order of what they grant. */
export type Role = "preview" | "readonly" | "commentor" | "edit" | "owner";

/** Every name `mode` accepts: the roles plus the legacy preset names. */
export type Mode = "preview" | "readonly" | "commentor" | "edit" | "owner" | "standalone" | "embedded" | "viewer";

/** Which of the editor's three review modes a capability set means. */
export type EditingMode = "editing" | "suggesting" | "viewing";

export declare const CAPABILITIES: readonly Capability[];
export declare const ROLES: readonly Role[];
export declare const PRESET_NAMES: readonly Mode[];
export declare const LEGACY_PRESETS: {
  standalone: "owner";
  viewer: "readonly";
  embedded: null;
};

export declare const DEFAULT_EDITOR_SRC: string;
export declare const OPENDOC_EDITOR_TAG: "opendoc-editor";
export declare const CAPABILITIES_EVENT: "opendoc-capabilities";

/**
 * Resolves the capability set for a page load.
 *
 * With no `mode`, `framed` decides: a page that is not the top window was put
 * there by someone else, and the safe reading of that is the embedded preset.
 * An unrecognised `mode` falls back to that same default, never to more.
 */
export declare function resolveCapabilities(input?: {
  mode?: Mode | string | null;
  framed?: boolean;
  autosave?: boolean | null;
}): Set<Capability>;

/** Maps a capability set onto the editor's existing three review modes. Fails
 *  closed to `"viewing"` for anything that is not a set. */
export declare function editingModeFor(capabilities: unknown): EditingMode;

/** The iframe `sandbox` tokens an embedding host should give a capability set. */
export declare function sandboxTokensFor(capabilities: unknown): readonly string[];

/** Reads `mode`, `autosave` and the framing off a real window. */
export declare function hostCapabilities(view?: unknown): Set<Capability>;

/** Detail carried by the `opendoc-capabilities` event, fired once per mount. */
export interface OpenDocCapabilitiesDetail {
  mode: string | null;
  capabilities: readonly Capability[];
  editingMode: EditingMode;
  sandbox: readonly string[];
  src: string;
}

/** An embedded opendoc editor.
 *
 *  `mode` is not called `role`: `role` is a global ARIA attribute, and
 *  `role="readonly"` would publish an invalid ARIA role to every assistive
 *  technology on the page.
 *
 *  Setting `mode` or `editor-src` after mount REMOUNTS. A permission handed
 *  over after the document is on screen was never a permission. */
export declare class OpenDocEditorElement extends HTMLElement {
  mode: string | null;
  readonly capabilities: readonly Capability[];
  readonly editingMode: EditingMode;
  readonly sandbox: readonly string[];
  readonly frame: HTMLIFrameElement | null;
  can(capability: Capability | string): boolean;
}

/** Registers the element. Idempotent, and returns whether this call was the one
 *  that registered it. */
export declare function defineOpenDocEditor(tag?: string): boolean;

declare global {
  interface HTMLElementTagNameMap {
    "opendoc-editor": OpenDocEditorElement;
  }
  interface HTMLElementEventMap {
    "opendoc-capabilities": CustomEvent<OpenDocCapabilitiesDetail>;
  }
}
