// GENERATED by webapp/tools/build-embed-package.mjs — do not edit.
//
// The unions below are emitted from the real exported values of
// webapp/src/capabilities.mjs, so a role or capability can never exist in the
// types without existing in the code, or the other way round.

/** Everything a host can grant or withhold. */
export type Capability = "open" | "new" | "save" | "download" | "print" | "edit" | "comment" | "branding" | "autosave";

/** The five roles, in strictly increasing order of what they grant. */
export type Role = "preview" | "readonly" | "commentor" | "edit" | "owner";

/** Every name `mode` accepts: the roles plus the legacy preset names. */
export type Mode = "preview" | "readonly" | "commentor" | "edit" | "owner" | "standalone" | "embedded" | "viewer";

/** Which of the editor's three review modes a capability set means. */
export type EditingMode = "editing" | "suggesting" | "viewing";

export declare const CAPABILITIES: readonly Capability[];
export declare const ROLES: readonly Role[];
export declare const PRESET_NAMES: readonly Mode[];
export declare const LEGACY_PRESETS: {
  standalone: "owner";
  viewer: "readonly";
  embedded: null;
};

export declare const DEFAULT_EDITOR_SRC: string;
export declare const OPENDOC_EDITOR_TAG: "opendoc-editor";
export declare const CAPABILITIES_EVENT: "opendoc-capabilities";

/**
 * Resolves the capability set for a page load.
 *
 * With no `mode`, `framed` decides: a page that is not the top window was put
 * there by someone else, and the safe reading of that is the embedded preset.
 * An unrecognised `mode` falls back to that same default, never to more.
 */
export declare function resolveCapabilities(input?: {
  mode?: Mode | string | null;
  framed?: boolean;
  autosave?: boolean | null;
}): Set<Capability>;

/** Maps a capability set onto the editor's existing three review modes. Fails
 *  closed to `"viewing"` for anything that is not a set. */
export declare function editingModeFor(capabilities: unknown): EditingMode;

/** The iframe `sandbox` tokens an embedding host should give a capability set. */
export declare function sandboxTokensFor(capabilities: unknown): readonly string[];

/** Reads `mode`, `autosave` and the framing off a real window. */
export declare function hostCapabilities(view?: unknown): Set<Capability>;

/** Detail carried by the `opendoc-capabilities` event, fired once per mount. */
export interface OpenDocCapabilitiesDetail {
  mode: string | null;
  capabilities: readonly Capability[];
  editingMode: EditingMode;
  sandbox: readonly string[];
  src: string;
}

/** An embedded opendoc editor.
 *
 *  `mode` is not called `role`: `role` is a global ARIA attribute, and
 *  `role="readonly"` would publish an invalid ARIA role to every assistive
 *  technology on the page.
 *
 *  Setting `mode` or `editor-src` after mount REMOUNTS. A permission handed
 *  over after the document is on screen was never a permission. */
export declare class OpenDocEditorElement extends HTMLElement {
  mode: string | null;
  readonly capabilities: readonly Capability[];
  readonly editingMode: EditingMode;
  readonly sandbox: readonly string[];
  readonly frame: HTMLIFrameElement | null;
  can(capability: Capability | string): boolean;
}

/** Registers the element. Idempotent, and returns whether this call was the one
 *  that registered it. */
export declare function defineOpenDocEditor(tag?: string): boolean;

// ---- The host contract (`docs/126` phase 2) --------------------------------
//
// The unions below are emitted from the real exported values of
// webapp/src/host_contract.mjs, for the same reason the capability unions are: a
// hand-written literal union is a second copy of the table that compiles happily
// while being wrong.

/** Every event a host can hear. */
export type HostEventName = "ready" | "change" | "selection" | "save" | "export" | "error" | "refusal";

/** Everything a refusal can say, as a code to branch on — never the message,
 *  which is localised and belongs to the chrome. */
export type RefusalCode = "unknown-command" | "capability-withheld" | "unavailable" | "engine-refused" | "threw" | "bad-request" | "timeout";

/** What a command can require of the host's grant. `mutate` is not a capability:
 *  it asks whether this page may change the document at all, which is granted by
 *  `edit` OR by `comment` (a commentor's changes are tracked suggestions). */
export type Requirement = "mutate" | "edit" | "comment" | "save" | "download" | "print" | "open" | "new" | "autosave";

export declare const CONTRACT_VERSION: number;
export declare const HOST_EVENT_NAMES: readonly HostEventName[];
export declare const REFUSAL_CODES: readonly RefusalCode[];
export declare const REQUIREMENTS: readonly Requirement[];

export interface Refusal {
  code: RefusalCode;
  command: string | null;
  requires: Requirement | null;
  /** Already localised, and for a person to read. Do not branch on it. */
  message: string;
}

export interface CommandResult {
  ok: boolean;
  command: string;
  /** The engine's revision watermark, or null when it could not be read. */
  revision: number | null;
  refusal?: Refusal;
}

export interface CommandState {
  id: string;
  /** In the contract at all. */
  known: boolean;
  /** In the registry right now — the table commands exist only with a caret in a
   *  table. Distinct from `granted`, which is about permission. */
  present: boolean;
  requires: Requirement | null;
  granted: boolean;
  available: boolean;
  /** The chrome's own reason when it is unavailable. */
  reason: string;
}

export interface HostEvent<Detail = Record<string, unknown>> {
  event: HostEventName;
  detail: Detail;
}

/** The editor, as a host addresses it. Both transports expose this. */
export interface OpenDocHostSession {
  describe(): Promise<unknown> | unknown;
  execute(id: string, args?: readonly unknown[]): Promise<CommandResult>;
  query(id: string): Promise<CommandState> | CommandState;
  ping(): Promise<unknown> | unknown;
  on(event: HostEventName, listener: (event: HostEvent) => void): () => void;
  off(event: HostEventName, listener: (event: HostEvent) => void): void;
}

/**
 * A client for an embedded editor, over `postMessage`.
 *
 * `editorOrigin` is REQUIRED and may not be `"*"`: the only default that would
 * always work is a wildcard, and posting document content to a wildcard target is
 * a decision no library should make for a host.
 */
export declare function createHostClient(io: {
  frame: HTMLIFrameElement | Window;
  editorOrigin: string;
  view?: Window;
  timeout?: number;
}): OpenDocHostSession & { dispose(): void; inFlight(): number };

/** Whether a capability set may run a command with this requirement. */
export declare function grantsRequirement(
  requires: Requirement | null,
  capabilities: unknown,
): boolean;

/** The contract row for a command id, or null when it is outside the contract. */
export declare function commandContract(
  id: string,
): { id: string; requires: Requirement | null; args: readonly object[]; family?: string } | null;

declare global {
  interface HTMLElementTagNameMap {
    "opendoc-editor": OpenDocEditorElement;
  }
  interface HTMLElementEventMap {
    "opendoc-capabilities": CustomEvent<OpenDocCapabilitiesDetail>;
  }
}
