// GENERATED by webapp/tools/build-embed-package.mjs — do not edit.
// Source of truth: webapp/src/capabilities.mjs
//
// Edit the source and re-run the tool. `embed_package.test.mjs` fails if
// this file is not byte-identical to a fresh generation, so a hand edit here
// is a build failure rather than a divergence nobody notices.

// What this editor is allowed to be, decided before the first paint.
//
// A framed editor is currently a STANDALONE editor: File ▸ New and File ▸ Open
// are live inside someone else's page, so a visitor can replace the host's
// document from within the host's own chrome. opencalc measured and fixed
// exactly this defect (`docs/104` §HF-109), and `docs/125` §2 F3 records it
// here — along with the two places that already know about framing and simply
// never generalised: autosave defaults off when framed, and one command already
// says "Autosave is off in an embedded editor".
//
// `docs/126` phase 1 makes this file the SINGLE authority for both of those
// questions rather than one of two places that know about framing. So the
// `autosave` capability now lives here beside the other seven, and the
// `?autosave=0` / `?autosave=1` contract (`docs/112` O-2) is resolved here too.
// There is deliberately no second mechanism: a caller that wants to know
// whether this page may keep drafts asks the capability set.
//
// It also carries the FIVE ROLES the owner asked for — `preview`, `readonly`,
// `commentor`, `edit`, `owner` — as presets over the same eight capabilities,
// not as a parallel concept. A role is a name for a subset; it is not a new
// kind of thing, and nothing downstream should ever branch on a role name.
//
// Pure: no DOM, no engine. The host inputs arrive as arguments so the whole
// resolution is answerable in node.

/** Everything a host can grant or withhold. Deliberately small — this is the
 *  v1 set `docs/125` §5.2 names, not a wish list. */
export const CAPABILITIES = Object.freeze([
  "open", // replace the loaded document from inside the editor
  "new", // start a blank document
  "save", // write the document back out
  "download", // export to a file the visitor keeps
  "print",
  "edit", // mutate the document at all
  "comment",
  "branding", // show OUR name and mark
  // Keep drafts on this origin. Was `autosaveAllowedHere()` in `main.js`, which
  // is the second place that knew about framing (`docs/126` phase 1). A framed
  // editor must not leave the visitor's typing in the host origin's store for a
  // later real session to be offered, so every framed preset withholds it.
  "autosave",
]);

/** The five roles, in strictly increasing order of what they grant.
 *
 *  The ordering is not decoration: `roles.test.mjs` asserts the chain is
 *  monotone, which is what stops the classic permissions defect where a
 *  "higher" role quietly loses something a lower one had. Add a role only where
 *  it belongs in the chain, or the guard will say so. */
export const ROLES = Object.freeze(["preview", "readonly", "commentor", "edit", "owner"]);

/** Role → capability set, and the three legacy preset names that predate the
 *  roles. The legacy names are kept because they are a published URL contract
 *  (`?mode=embedded`), and two of them are exact aliases; `embedded` is not,
 *  and the difference is the point — see its comment. */
const PRESETS = Object.freeze({
  // ── The five roles ────────────────────────────────────────────────────────
  //
  // Look, and nothing else. `docs/83` §2 describes read-only/preview as the
  // runtime acting "strictly as a layout and rendering engine"; scrolling,
  // zooming, selecting, copying and searching are not in the capability set at
  // all because nobody gates them, so a preview grants none of the eight and
  // is still a usable reader.
  preview: Object.freeze([]),
  // A published document: read it, and take a paper copy. `download` is
  // withheld deliberately — a reader who can download holds the file, which is
  // a different grant from being allowed to look at it, and a host that wants
  // to hand the file over says `commentor` or wires the file itself.
  readonly: Object.freeze(["print"]),
  // Google Docs' "Commenter" and Word's review reviewer: may annotate and may
  // suggest, may not change the document outright. That maps onto the editor's
  // EXISTING Suggesting mode (see `editingModeFor`), where every body change is
  // recorded as a tracked revision the owner accepts or rejects.
  commentor: Object.freeze(["print", "download", "comment"]),
  // The reason a host embeds an editor. It may change and keep the document; it
  // may not reach for a DIFFERENT one, and it does not advertise us inside
  // their product.
  edit: Object.freeze(["save", "download", "print", "edit", "comment", "autosave"]),
  // The page is ours, or the host has said it may as well be.
  owner: Object.freeze([...CAPABILITIES]),

  // ── The legacy preset names ───────────────────────────────────────────────
  //
  // `standalone` is `owner`: a page opened directly, with no host and no
  // question to answer.
  standalone: Object.freeze([...CAPABILITIES]),
  // `embedded` is the `edit` role MINUS `autosave`, and that is exactly what it
  // has always meant: it is the default for a page that turned out to be framed
  // without anyone asking for a mode, and a framed page must not leave drafts
  // in the host's origin. A host that has thought about it and wants drafts
  // says `?mode=edit`, or `?autosave=1`.
  embedded: Object.freeze(["save", "download", "print", "edit", "comment"]),
  // `viewer` is `readonly`.
  viewer: Object.freeze(["print"]),
});

/** The legacy name → role it is an alias of, or `null` where it is not an exact
 *  alias of any role. Exported so a guard can prove the aliases really are
 *  equal sets rather than two tables that drifted. */
export const LEGACY_PRESETS = Object.freeze({
  standalone: "owner",
  viewer: "readonly",
  embedded: null, // `edit` minus `autosave` — see the comment above
});

/** The preset names a host may ask for, for validation and for tests. */
export const PRESET_NAMES = Object.freeze(Object.keys(PRESETS));

// ---- Surface composition ---------------------------------------------------
//
// `docs/126`'s container policy, owner notes §2, draws a line this file did not
// have: **surface composition is a different question from command gating.**
//
//   * Within a surface a role DOES get, a command that cannot run right now is
//     disabled and says why. That is "never a dead control" (`SKILL` §10), it is
//     what `reflectReviewModeAccess` below already does, and it is correct.
//   * A role with no business with a WHOLE SURFACE does not get the surface. A
//     `readonly` container has no editing ribbon — not a ribbon full of greyed
//     buttons, no ribbon. Word, Google Docs and ONLYOFFICE all present read-only
//     as different chrome, not the editing chrome dimmed.
//
// The distinction is "never, for you" versus "not right now", and a wall of
// greyed controls is not honesty: it tells a reader about capabilities they will
// never have and buries the one or two things they can do.
//
// SO THE TWO AXES ARE SEPARATE, AND BOTH RESOLVE HERE. A region is not a
// capability and must never be made one: a withheld region is a presentation
// decision the host made about their page, and a withheld capability is a
// permission. Collapsing them would make every hidden band read as a refusal —
// and, worse, would let a host defeat a permission by showing a surface.
//
// NAMING. Not "surface": in this codebase `surface` already means which command
// menu a row appears on (`editorCommands({ surface: "palette" | "menu" | … })`),
// and overloading it would make "is this capability reachable from two surfaces"
// (`105` UX-004) ambiguous. `docs/126` says surfaces; the code says REGIONS.

/** Every region of the chrome a host can withhold.
 *
 *  Each one is a whole presentation, not a control: the unit is "a reader has no
 *  business with this at all". Deliberately not one entry per button — that is
 *  what the capability set and the command registry are for.
 *
 *  The eight `band.*` entries are the ribbon's tabs, which is what this project
 *  calls a band ("the Home band must fit 1280px"). A band is the right grain for
 *  a host: "show Home and Insert only" is a real request, where "hide the third
 *  group inside Home" is a request to redesign the ribbon. */
export const REGIONS = Object.freeze([
  "brand", // the product mark in the top bar
  "title", // the document name, and renaming it
  "menu", // the application menu bar — one of the two navigation axes
  "ribbon", // the whole tabbed ribbon, strip and bands together
  "band.file",
  "band.home",
  "band.insert",
  "band.layout",
  "band.references",
  "band.review",
  "band.view",
  "band.table",
  "rail", // the left navigation rail and its panels: outline, pages
  "status", // the status bar
  "zoom", // the zoom cluster in the status bar
  "find", // the find/replace card
  "selection", // the floating selection toolbar
  "settings", // the settings dialog and its trigger
]);

/** Regions that are only meaningful inside the ribbon, so withholding `ribbon`
 *  withholds them too. Derived, not listed twice. */
const BAND_REGIONS = Object.freeze(REGIONS.filter((id) => id.startsWith("band.")));

/** Every region — the presentation a page with no host gets. */
const ALL_REGIONS = Object.freeze([...REGIONS]);

/** READING CHROME, for `readonly`.
 *
 *  `docs/126` spells out what it is: "navigation, outline, find, zoom, page
 *  controls, print" — a reading experience, where the reader navigates and
 *  searches and a static image could not replace it. So: the menu bar rather
 *  than the ribbon, because that is where File ▸ Print lives and because a
 *  reader needs exactly one navigation axis, never two (`109` UX-014, `docs/122`,
 *  and the invariant `style.css` states above its compact/ribbon rules). The
 *  rail carries the outline and the page thumbnails; the status bar carries the
 *  page count and the zoom; the find card is how a reader searches.
 *
 *  Not here: the ribbon and every band, the floating selection toolbar (it offers
 *  formatting), and Settings (appearance, reviewer identity, autosave and
 *  proofing are an author's preferences). */
const READING_REGIONS = Object.freeze(["brand", "title", "menu", "rail", "status", "zoom", "find"]);

/** PREVIEW CHROME.
 *
 *  Empty, and that is the point. `docs/126` is explicit that `preview` and
 *  `readonly` are NOT the same thing and must not be collapsed: `preview` is the
 *  runtime as a layout and rendering engine — a picture of the document, for a
 *  thumbnail, an attachment preview, a search result — and its own test of the
 *  difference is "could a static image replace it? For `preview`, nearly."
 *  Giving it reading chrome would hand every attachment preview a navigation UI
 *  it does not want; giving `readonly` a bare canvas would leave a published
 *  document with no way to reach page 40. */
const PREVIEW_REGIONS = Object.freeze([]);

/** Preset → regions. Same table shape as the capability presets, and the same
 *  rule: nothing downstream branches on a role NAME, it asks for the set. */
const REGION_PRESETS = Object.freeze({
  preview: PREVIEW_REGIONS,
  readonly: READING_REGIONS,
  // A commentor suggests, and a suggestion is a document change recorded as a
  // tracked revision — so they need the formatting chrome an author needs. The
  // capability set is what stops them committing it outright.
  commentor: ALL_REGIONS,
  edit: ALL_REGIONS,
  owner: ALL_REGIONS,
  standalone: ALL_REGIONS,
  embedded: ALL_REGIONS,
  viewer: READING_REGIONS,
});

/**
 * Parses a withhold list: `"-print,-download"` or `"print,download"`.
 *
 * ONE DIRECTION, ALWAYS. A list can only take things away, whether or not the
 * entries carry their minus sign, because a configuration channel that can widen
 * a role is a configuration channel an attacker fills in. `docs/125` §5.2 states
 * the rule for capabilities — "`can` may only narrow the role. A host cannot
 * grant `edit` to `preview` by accident, and there is exactly one direction to
 * audit" — and it holds for regions for the same reason plus one more: a
 * `preview` with a ribbon is not a presentation anybody asked for.
 *
 * An unknown entry is DROPPED rather than refused, and dropping narrows nothing,
 * so a typo in a host's URL can never widen the result. The same reasoning as an
 * unrecognised `mode` falling back to the framed default.
 *
 * Complexity: O(entries).
 *
 * @param {string|null|undefined} raw
 * @param {readonly string[]} known the vocabulary; anything else is dropped.
 * @returns {readonly string[]}
 */
export function parseWithheld(raw, known) {
  const out = [];
  for (const entry of String(raw ?? "").split(",")) {
    const name = entry.trim().replace(/^-/, "");
    if (!name) continue;
    if (!known.includes(name)) continue;
    if (!out.includes(name)) out.push(name);
  }
  return Object.freeze(out);
}

/**
 * Resolves the capability set for this page load.
 *
 * `mode` is the host's explicit request (`?mode=embedded`, `?mode=readonly`) —
 * a role name or a legacy preset name. When absent, being FRAMED decides it: a
 * page that is not the top window was put there by someone else, and the safe
 * reading of that is `embedded`, not `standalone`. That default is the whole
 * point — it closes the defect without a host having to know this parameter
 * exists.
 *
 * An unrecognised `mode` falls back to the framed-derived default rather than
 * throwing: a typo in a host's URL must not leave the editor with no chrome at
 * all, and it must not silently grant MORE than the default either.
 *
 * `autosave` is the one per-capability override in v1, because it is an already
 * published contract (`docs/112` O-2) and absorbing it here is what makes this
 * file the single authority instead of the second place that knows about
 * framing. It can only move `autosave`, never anything else, so a host cannot
 * widen a role through it.
 *
 * Complexity: O(1).
 *
 * @param {{mode?: string|null, framed?: boolean, autosave?: boolean|null}} [input]
 * @returns {Set<string>}
 */
export function resolveCapabilities({ mode = null, framed = false, autosave = null, withhold = null } = {}) {
  const asked = typeof mode === "string" ? mode.trim().toLowerCase() : "";
  const preset = PRESETS[asked] ?? PRESETS[framed ? "embedded" : "standalone"];
  const granted = new Set(preset);
  if (autosave === true) granted.add("autosave");
  else if (autosave === false) granted.delete("autosave");
  // THE PER-CAPABILITY POLICY (`docs/126` container policy §1). "Print,
  // download, save, edit and comment withholdable independently" — "comments
  // only, everything else off" is a real configuration, not a rung on a ladder.
  //
  // It is applied HERE, after the preset, which is what makes the roles presets
  // over the capability set rather than a parallel mechanism: a role is the
  // starting set, a withhold list narrows it, and there is one function that
  // answers "what may this page do". Two code paths — one for roles, one for
  // explicit lists — would disagree exactly the way the `shortcut:` labels and
  // the key bindings did.
  for (const name of parseWithheld(withhold, CAPABILITIES)) granted.delete(name);
  return granted;
}

/**
 * The chrome regions this page load gets.
 *
 * The same shape as `resolveCapabilities`, from the same `mode`, in the same
 * file, because "one authority" has to mean one place that knows what a role is.
 * A role names two sets, and a caller asks for whichever it needs.
 *
 * Complexity: O(1) plus O(withheld).
 *
 * @param {{mode?: string|null, framed?: boolean, withhold?: string|null}} [input]
 * @returns {Set<string>}
 */
export function resolveRegions({ mode = null, framed = false, withhold = null } = {}) {
  const asked = typeof mode === "string" ? mode.trim().toLowerCase() : "";
  const preset = REGION_PRESETS[asked] ?? REGION_PRESETS[framed ? "embedded" : "standalone"];
  const shown = new Set(preset);
  for (const id of parseWithheld(withhold, REGIONS)) shown.delete(id);
  // The ribbon's bands are inside the ribbon, so withholding the ribbon
  // withholds them. Derived rather than asked of the host twice: a host who
  // said `-ribbon` and still saw a band would have found a hole, and a host who
  // had to say `-ribbon,-band.home,-band.insert,…` would be maintaining our
  // containment rules for us.
  if (!shown.has("ribbon")) for (const id of BAND_REGIONS) shown.delete(id);
  return shown;
}

/**
 * Which of the editor's three review modes a capability set means.
 *
 * This is the whole of how a role is enforced, and it deliberately invents
 * nothing: Editing / Suggesting / Viewing already exist, and Viewing is already
 * fully read-only at one fail-closed choke point — `blockMutationInViewing()`
 * refuses every mutation path (typing, deletion, paste, toolbar formatting,
 * table ops, comment and revision decisions) rather than relying on any
 * individual control being disabled (`docs/68` §"Suggesting mode",
 * REVIEW-GAP-014). So a role does not need a gate of its own; it needs to pick
 * the right existing mode, and a chrome defeated from devtools still meets that
 * choke point.
 *
 *   `edit`    → Editing     — change the document outright.
 *   `comment` → Suggesting  — annotate, and change it as tracked revisions.
 *   neither   → Viewing     — no Operation reaches apply.
 *
 * Complexity: O(1).
 *
 * @param {{has: (name: string) => boolean}} capabilities
 * @returns {"editing"|"suggesting"|"viewing"}
 */
export function editingModeFor(capabilities) {
  if (grants(capabilities, "edit")) return "editing";
  if (grants(capabilities, "comment")) return "suggesting";
  return "viewing";
}

/**
 * Whether a capability set allows a review MODE to be chosen.
 *
 * Viewing is always allowed — a reader may always read. Suggesting needs
 * `comment`; Editing needs `edit`. The inverse of [`editingModeFor`]: that one
 * picks the strongest mode a host permits, this one answers whether a
 * particular mode is among them, which is what a mode CONTROL has to know to
 * disable itself with a reason rather than vanish.
 *
 * Complexity: O(1).
 *
 * @param {{has: (name: string) => boolean}} capabilities
 * @param {string} mode
 * @returns {boolean}
 */
export function allowsMode(capabilities, mode) {
  if (mode === "suggesting") return grants(capabilities, "comment");
  if (mode === "editing") return grants(capabilities, "edit");
  return true;
}

/**
 * Reflects a host's grant onto the review-mode buttons: a mode the host
 * withheld is DISABLED WITH A REASON, never removed.
 *
 * Here rather than in `main.js` because it is the same question as
 * `allowsMode` asked of the DOM, and because putting it here makes "a withheld
 * mode still appears, and says why" answerable without a browser. A control
 * that silently vanishes is worse than one that explains itself, and a host
 * reading a missing button cannot tell a permission from a bug.
 *
 * `readOnlyReason` (the engine refusing the whole document) outranks a
 * host-withheld mode: it is the more specific truth and names the document.
 *
 * Complexity: O(buttons).
 */
export function reflectReviewModeAccess({ buttons, capabilities, readOnlyReason, withheldReason }) {
  for (const button of buttons ?? []) {
    const withheld = !allowsMode(capabilities, button.dataset?.reviewMode);
    button.disabled = !!readOnlyReason || withheld;
    if (readOnlyReason) button.title = readOnlyReason;
    else if (withheld) button.title = withheldReason;
    else button.removeAttribute("title");
  }
}

/** Whether a capability set grants `name`, for any value at all.
 *
 *  Fail closed on a shape that is not a set. A caller that has not resolved
 *  anything yet — or has been handed a plain object by a host — must get "no",
 *  not a `TypeError` that the caller's own `catch` then turns into whatever its
 *  fallback happens to be. An exception on the permission path is a permission
 *  decided by accident. */
function grants(capabilities, name) {
  try {
    return capabilities?.has?.(name) === true;
  } catch {
    return false;
  }
}

/** The iframe `sandbox` tokens an embedding host should give this capability
 *  set.
 *
 *  A third enforcement layer, and the only one the page cannot argue with: the
 *  BROWSER refuses a download the sandbox did not allow, whatever the chrome or
 *  the engine think. ONLYOFFICE's `createIframe` sets no `sandbox` attribute at
 *  all (`reference/web-apps/apps/api/documents/api.js:1278`), so this is a
 *  layer they do not have.
 *
 *  `allow-scripts` and `allow-same-origin` are unconditional: without them the
 *  editor cannot run its own WebAssembly or read its own origin, and an embed
 *  that cannot boot is not a permission decision. Together they do mean the
 *  frame can reach out of the sandbox, which is why the sandbox is a LAYER and
 *  not the enforcement.
 *
 *  Complexity: O(1).
 *
 *  @param {{has: (name: string) => boolean}} capabilities
 *  @returns {readonly string[]}
 */
export function sandboxTokensFor(capabilities) {
  const tokens = ["allow-scripts", "allow-same-origin"];
  // Saving and exporting both end in a file the visitor keeps.
  if (grants(capabilities, "download") || grants(capabilities, "save")) tokens.push("allow-downloads");
  // The print dialog is a modal the frame opens.
  if (grants(capabilities, "print")) tokens.push("allow-modals");
  return Object.freeze(tokens);
}

/** The host inputs carried on the page's URL, read once.
 *
 *  `mode` and `autosave` were already a published contract; `can` and `chrome`
 *  join them, spelled the same way and read in the same place, because `?lang=`
 *  already set the precedent that a host's configuration travels in the URL and
 *  because that is the only channel that is decided BEFORE the frame's first
 *  navigation (`embed_element.mjs`). A second channel — a `postMessage` after
 *  load — would mean a window in which the editor was something else, and
 *  `docs/104` is explicit that gating must apply before the first frame. */
export function hostConfig(view = globalThis) {
  const search = view?.location?.search ?? "";
  let params = null;
  try {
    params = new URLSearchParams(search);
  } catch {
    params = null;
  }
  const asked = params?.get("autosave") ?? null;
  // `window.self !== window.top` throws on a cross-origin parent in some
  // engines; a throw means we ARE framed, which is the safer answer anyway.
  let framed = false;
  try {
    framed = view.self !== view.top;
  } catch {
    framed = true;
  }
  return {
    mode: params?.get("mode") ?? null,
    autosave: asked === "1" ? true : asked === "0" ? false : null,
    withhold: params?.get("can") ?? null,
    chrome: params?.get("chrome") ?? null,
    framed,
  };
}

/** Reads the host inputs off a real page. Separated from `resolveCapabilities`
 *  so the decision itself stays pure and testable. */
export function hostCapabilities(view = globalThis) {
  return resolveCapabilities(hostConfig(view));
}

/** The regions a real page shows, from the same inputs. */
export function hostRegions(view = globalThis) {
  const config = hostConfig(view);
  return resolveRegions({ mode: config.mode, framed: config.framed, withhold: config.chrome });
}
