// GENERATED by webapp/tools/build-embed-package.mjs — do not edit.
// Source of truth: webapp/src/embed_define.js
//
// Edit the source and re-run the tool. `embed_package.test.mjs` fails if
// this file is not byte-identical to a fresh generation, so a hand edit here
// is a build failure rather than a divergence nobody notices.

// The side-effect entry point: `import "@casualoffice/opendoc-embed/define"`
// and `<opendoc-editor>` works.
//
// Separate from the main entry so that one has no side effects and stays
// tree-shakeable — a host that wants the class, the capability tables or the
// role→mode mapping without registering a tag imports the package root.
import { defineOpenDocEditor } from "./embed_element.mjs";

defineOpenDocEditor();
