// SPDX-License-Identifier: Apache-2.0
// GENERATED by webapp/tools/build-embed-package.mjs — do not edit.
//
// What a host installed, what it speaks, and what it was built from — in one
// place, derived from the files that decide each one.
//
// THREE NUMBERS, DELIBERATELY NOT ONE. `version` is what npm resolved.
// `contract` is what the editor speaks, and it is stable across package
// releases on purpose: an added command, event or refusal code is additive
// (`docs/05` §12), so tying it to the package version would make hosts re-pin for
// changes that break nothing. `engine` is the Rust workspace the WebAssembly came
// from. Collapsing them would make two of the three lie.
//
// No build commit here. It is stamped at DEPLOY time from `GITHUB_SHA`
// (`webapp/stamp-assets.py`), and a committed file claiming a commit would be a
// fabricated provenance of exactly the kind `docs/99` §9 exists to prevent.
export const RELEASE = Object.freeze({
  "package": "@casualoffice/opendoc-embed",
  "version": "0.1.0",
  "contract": 1,
  "engine": "0.0.1",
  "licence": "Apache-2.0",
  "repository": "git+https://github.com/CasualOffice/opendoc.git"
});
