import { test, expect, gotoEditor, clickIntoFirstPage, setReviewMode, MOD } from './fixtures.mjs';
async function panel(page) {
  await page.locator('#paraOptsBtn').click();
  await expect(page.locator('#paragraphPropertiesPanel')).toBeVisible();
}
test('paragraph direction, pagination and outline persist through closing, clear and undo', async ({page}) => {
  await gotoEditor(page);
  await clickIntoFirstPage(page);
  await panel(page);
  const inheritedOutline = await page.locator('#paraOutline').inputValue();
  await page.locator('#paraDirection').selectOption('true');
  await page.locator('#paraWidow').uncheck();
  await page.locator('#paraContextual').check();
  await page.locator('#paraOutline').selectOption('2');
  await page.locator('#paragraphPropertiesClose').click();
  await panel(page);
  await expect(page.locator('#paraDirection')).toHaveValue('true');
  await expect(page.locator('#paraWidow')).not.toBeChecked();
  await expect(page.locator('#paraContextual')).toBeChecked();
  await expect(page.locator('#paraOutline')).toHaveValue('2');
  await page.locator('#paraClearAll').click();
  await expect(page.locator('#paraDirection')).toHaveValue('false');
  await expect(page.locator('#paraOutline')).toHaveValue(inheritedOutline);
  await page.locator('#paragraphPropertiesClose').click();
  await page.locator('#undoBtn').click();
  await panel(page);
  await expect(page.locator('#paraDirection')).toHaveValue('true');
  await expect(page.locator('#paraOutline')).toHaveValue('2');
});
test('tab leader and document default interval are read from the edited document', async ({page}) => {
  await gotoEditor(page);
  await clickIntoFirstPage(page);
  await page.keyboard.press(`${MOD}+Shift+P`);
  await page.locator('#cmdInput').fill('tab stops');
  await page.locator('[data-command-id="layout.tabStops"]').click();
  await page.locator('#tabStopsDefault').fill('0.75');
  await page.locator('#tabStopsPosition').click();
  await page.locator('#tabStopsPosition').fill('2');
  await page.locator('#tabStopsLeader').selectOption('1');
  await page.locator('#tabStopsSet').click();
  await page.locator('#tabStopsList [data-position="2880"]').click();
  await expect(page.locator('#tabStopsLeader')).toHaveValue('1');
  await expect(page.locator('#tabStopsDefault')).toHaveValue('0.75');
});
test('paragraph border choices persist and undo restores their previous properties', async ({page}) => {
  await gotoEditor(page);
  await clickIntoFirstPage(page);
  await panel(page);
  await page.locator('#paraBorderStyle').selectOption('double');
  await page.locator('#paraBorderWidth').fill('1.5');
  await page.locator('#paraBorderPadding').fill('7');
  await page.locator('#paraBorderBetween').click();
  await expect(page.locator('#paraBorderBetween')).toHaveAttribute('aria-pressed','true');
  await page.locator('#paragraphPropertiesClose').click();
  await panel(page);
  await expect(page.locator('#paraBorderStyle')).toHaveValue('double');
  await expect(page.locator('#paraBorderWidth')).toHaveValue('1.5');
  await expect(page.locator('#paraBorderPadding')).toHaveValue('7');
  await page.locator('#paraBorderWidth').fill('2');
  await page.locator('#paraBorderBetween').click();
  await page.locator('#paragraphPropertiesClose').click();
  await page.locator('#undoBtn').click();
  await panel(page);
  await expect(page.locator('#paraBorderWidth')).toHaveValue('1.5');
});
test('selected text direction is authored by the inspector and restored by undo', async ({page}) => {
  await gotoEditor(page);
  await clickIntoFirstPage(page);
  await page.keyboard.type('Direction');
  await page.keyboard.press(`${MOD}+a`);
  await panel(page);
  await page.locator('#runDirectionRtl').click();
  await expect(page.locator('#runDirectionRtl')).toHaveAttribute('aria-pressed','true');
  await page.locator('#paragraphPropertiesClose').click();
  await panel(page);
  await expect(page.locator('#runDirectionRtl')).toHaveAttribute('aria-pressed','true');
  await page.locator('#runDirectionLtr').click();
  await expect(page.locator('#runDirectionLtr')).toHaveAttribute('aria-pressed','true');
  await page.locator('#paragraphPropertiesClose').click();
  await page.locator('#undoBtn').click();
  await panel(page);
  await expect(page.locator('#runDirectionRtl')).toHaveAttribute('aria-pressed','true');
});
test('default tab interval refuses untracked changes in Suggesting and restores its value', async ({page}) => {
  await gotoEditor(page);
  await clickIntoFirstPage(page);
  await setReviewMode(page,'suggesting');
  await page.keyboard.press(`${MOD}+Shift+P`);
  await page.locator('#cmdInput').fill('tab stops');
  await page.locator('[data-command-id="layout.tabStops"]').click();
  const before = await page.locator('#tabStopsDefault').inputValue();
  await page.locator('#tabStopsDefault').fill('0.75');
  await page.locator('#tabStopsPosition').click();
  await expect(page.locator('#tabStopsDefault')).toHaveValue(before);
  await expect(page.locator('#status')).toContainText(/suggest|track|editing/i);
});
