// Headers and footers across a SECTION BREAK — the reported bug, in the browser.
//
// Verbatim report: "header and footer … on orientation change … it breaks. Like
// if page 5 has changed orientation, if I change header on page 3, pages 5 and
// after that, header and footer won't change."
//
// Running content is per section (`w:headerReference` lives in `w:sectPr`), and a
// document that turns landscape part-way has more than one section. Every
// running-content surface in the editor resolved the FIRST section instead of the
// section owning the page the user was on, so a command aimed at the page in front
// of the user changed a page somewhere else — and the page they asked about never
// changed. That is the docs/104 T-01 body-vs-surface class.
//
// The fixture (`?fixture=sections`, generated by the `generate_sections_fixture_docx`
// engine test) is four portrait pages whose section owns "PORTRAIT HEADER" /
// "PORTRAIT FOOTER", then two LANDSCAPE pages whose section owns its own default
// header, its own first-page header and its own footer, with 2" vertical margins
// against the portrait section's 1".
import { test, expect, MOD, documentPageCount, pageSheet } from "./fixtures.mjs";

const LANDSCAPE_PAGE = 4; // 0-based: page 5, the first page of the landscape section
const PORTRAIT_PAGE = 0;

async function gotoSections(page) {
  await page.goto("/editor.html?fixture=sections");
  await page.waitForFunction(
    () => {
      const status = document.getElementById("status");
      return (
        status !== null &&
        status.textContent === "" &&
        document.querySelectorAll(".page-wrap").length > 0 &&
        document.body.dataset.fontsReady === "true"
      );
    },
    null,
    { timeout: 45_000 },
  );
  // The document's own page count, not the number of sheets on screen: only
  // the pages near the viewport have sheets (`docs/113` §8.6).
  expect(await documentPageCount(page)).toBe(6);
}

/** A locator for one page's sheet, addressed by the page it IS rather than by
 *  its position among the sheets that happen to exist. */
function sheetOf(page, index) {
  return page.locator(`#pages .page-wrap[data-page-number="${index + 1}"]`);
}

async function runCommand(page, label) {
  await page.keyboard.press(`${MOD}+Shift+P`);
  await expect(page.locator("#cmdPalette")).toBeVisible();
  await page.locator("#cmdInput").fill(label);
  await page.locator("#cmdList .cmd-item", { hasText: label }).first().click();
  await expect(page.locator("#cmdPalette")).toBeHidden();
}

/** Brings one page into the middle of the viewport — what "the page I am on"
 *  means to both the user and `pageInView()` — and waits for its raster. */
async function showPage(page, index) {
  // Scroll the page into existence first: a page outside the viewport has no
  // sheet at all, so there is nothing to call `scrollIntoView` on.
  await pageSheet(page, index + 1);
  await sheetOf(page, index).evaluate((element) => element.scrollIntoView({ block: "center" }));
  // Re-query rather than reuse a handle: the scroll can recycle the sheet.
  await expect.poll(() => sheetOf(page, index).locator("canvas.page").count()).toBe(1);
}

/** An ink signature of the top band of a page's raster: how many dark pixels it
 *  holds and where they sit. Compares what the HEADER actually paints, rather
 *  than trusting any host state — the previous specs were green while the wrong
 *  body was being edited precisely because they only asserted host state. */
async function headerInk(page, index) {
  await showPage(page, index);
  return page.evaluate((i) => {
    const canvas = document
      .querySelector(`#pages .page-wrap[data-page-number="${i + 1}"]`)
      .querySelector("canvas.page");
    const band = Math.max(1, Math.round(canvas.height * 0.22));
    const data = canvas.getContext("2d").getImageData(0, 0, canvas.width, band).data;
    let ink = 0;
    let moment = 0;
    for (let p = 0; p < data.length; p += 4) {
      if ((data[p] + data[p + 1] + data[p + 2]) / 3 < 160) {
        ink += 1;
        moment += (p / 4) % canvas.width;
      }
    }
    return `${ink}:${moment}`;
  }, index);
}

/** A page's dashed running-band overlay height as a fraction of the sheet — the
 *  band is a margin, so the fraction is section geometry and zoom-independent. */
async function bandFraction(page, index) {
  await pageSheet(page, index + 1);
  return page.evaluate((i) => {
    const wrap = document.querySelector(`#pages .page-wrap[data-page-number="${i + 1}"]`);
    const band = wrap.querySelector(".running-band");
    if (!band) return null;
    return band.getBoundingClientRect().height / wrap.getBoundingClientRect().height;
  }, index);
}

test("the header band belongs to its own section: named, and drawn in that section's margin", async ({
  page,
  consoleErrors,
}) => {
  await gotoSections(page);

  // Enter the header from page 1, the ordinary gesture.
  const portrait = page.locator(".page-wrap .page").first();
  const box = await portrait.boundingBox();
  await portrait.dblclick({ position: { x: box.width * 0.5, y: box.height * 0.04 } });
  await expect(page.locator("#pages")).toHaveAttribute("data-running-edit", "header");

  // Word names the section on the band once a document has more than one, which
  // is the only thing on screen that can explain why two pages show different
  // headers. Every page said just "Header".
  await pageSheet(page, PORTRAIT_PAGE + 1);
  await expect(sheetOf(page, PORTRAIT_PAGE).locator(".running-band-label"))
    .toHaveText(/Section 1/);
  await pageSheet(page, LANDSCAPE_PAGE + 1);
  await expect(sheetOf(page, LANDSCAPE_PAGE).locator(".running-band-label"))
    .toHaveText(/Section 2/);

  // And the dashed boundary is that page's OWN top margin: 1" of an 11" portrait
  // sheet, 2" of an 8.5" landscape one. Both bands used to be drawn from the
  // first section's margins, so the landscape pages drew it in the wrong place.
  expect(await bandFraction(page, PORTRAIT_PAGE)).toBeCloseTo(1440 / 15840, 2);
  expect(await bandFraction(page, LANDSCAPE_PAGE)).toBeCloseTo(2880 / 12240, 2);

  expect(consoleErrors).toEqual([]);
});

test("Different first page applies to the section the user is on", async ({
  page,
  consoleErrors,
}) => {
  await gotoSections(page);
  const portraitBefore = await headerInk(page, PORTRAIT_PAGE);
  const landscapeBefore = await headerInk(page, LANDSCAPE_PAGE);

  // On page 5 — the landscape section's first page — ask for a distinct
  // first-page header. `w:titlePg` is per SECTION, so this is a question about
  // the section the user is reading; it used to always flip the first section,
  // which changed a page the user was not looking at and left this one alone.
  await showPage(page, LANDSCAPE_PAGE);
  await runCommand(page, "Different first page");
  await expect(page.locator("#status")).toContainText("Different first page on");

  await expect
    .poll(() => headerInk(page, LANDSCAPE_PAGE))
    .not.toBe(landscapeBefore);
  expect(await headerInk(page, PORTRAIT_PAGE)).toBe(portraitBefore);

  expect(consoleErrors).toEqual([]);
});
